### ISSUE TITLE
Error if the parameter value is filled

### ISSUE THREAD

**Issue by atomoc** [Jako/multiTV#120]
If the existing option to assign multitv and resource present value, an error will occur.

**Comment by Jako** [comment]
Hope I understand your problem right: You can't change an already filled existing template variable to a custom template variable of multiTV type. multiTV expects a JSON encoded value in that TV and won't work on it – the template variable value has to be empty.

**Comment by atomoc** [comment]
Yes. It would be correct if the field with the wrong values ​​did not violate the program.

**Comment by Jako** [comment]
Delete the existing template variable and create it again.

**Comment by atomoc** [comment]
It does not, its use of resources, and in 1500 it important data.

**Comment by Jako** [comment]
You can’t transform a TV into a multiTV this way.

**Comment by atomoc** [comment]
Yes, due to an error that occurs in each resource uses this field.

**Comment by atomoc** [comment]
https://www.dropbox.com/s/fzm0dpqv4ab1ol4/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%20%D0%BE%D1%82%202015-01-22%2023%3A47%3A32.png?dl=0

**Comment by Jako** [comment]
If you want to modify the content of a normal TV to the content of a multiTV you have to change the value of that TV.

You could look into the code of the updateTV snippet and change it to your needs.

In your screenshot the first TV is a not transformed normal TV. This causes an error in multiTV script code so it does not run for the second TV.

**Comment by atomoc** [comment]
That's right. The question is whether you can do without errors?

**Comment by Jako** [comment]
Transform the first TV into a multiTV and the error is gone.

You just have to change the marked lines in https://github.com/Jako/multiTV/blob/master/assets/tvs/multitv/updatetv.snippet.php#L53-L68 to i.e.

$tvValues->fieldValue['whatever_new_key'] = $row['value‘];

And the old TV is transformed into multiTV with whatever_new_key containing the old value.

**Comment by Jako** [comment]
Transform the first TV into a multiTV and the error is gone.

You just have to change the marked lines in https://github.com/Jako/multiTV/blob/master/assets/tvs/multitv/updatetv.snippet.php#L53-L68 to i.e.

```
$tvValues->fieldValue['whatever_new_key'] = htmlentities($row['value‘]);
```

And the old TV is transformed into multiTV with `whatever_new_key` containing the old value.

Backup your database before running that script.

**Comment by atomoc** [comment]
How to run a script?

**Comment by atomoc** [comment]
I did not understand.

**Comment by Jako** [comment]
- Create a new snippet called transformTV
- Insert the code from https://raw.githubusercontent.com/Jako/multiTV/master/assets/tvs/multitv/updatetv.snippet.php
- Change the lines 53-68 to
```
$tvValues = new stdObject();
$tvValues->fieldValue['whatever_new_key'] = htmlentities($row['value‘]);
```
- Run it with in a blank new resource.
```
[!transformTV?
&tvNames=`yourOldTVname1,yourOldTVname2`
!]
```
- http://jako.github.io/multiTV/donate.html if it works.

**Comment by Jako** [comment]
Edited the code above …

**Comment by atomoc** [comment]
Not work

**Comment by atomoc** [comment]
Is it possible to make sure that the program continues to run? If there is an incorrect value.

**Comment by atomoc** [comment]
Although you're right, it is necessary to deal with the snippet. The question is, why did not the module?

**Comment by Jako** [comment]
Don’t understand the last message.

**Comment by atomoc** [comment]
Sorry, it's not me, it's google) Do not get me transform values ​​through the snippet, but we must do it.

**Comment by Jako** [comment]
Try these lines:
```
$tvValues = new stdObject();
$tvValues->fieldValue = array(array('whatever_new_key' => htmlentities($row['value‘])));
```

**Comment by atomoc** [comment]
tvName: ourPhone
multiTV:
```php
<?php
$settings['display'] = 'vertical';
$settings['fields'] = array(
    'phone' => array(
        'caption' => 'Номер',
        'type' => 'text'
    ));

$settings['configuration'] = array(
    'enablePaste' => false,
    'enableClear' => true
);
```
Snippet call:
```php
[!transformTV?
    &tvNames=`ourPhone`
!]
```
Change updatetv.snippet.php the lines 53-68 to:
```php
$tvValues = new stdObject();
$tvValues->fieldValue = array(array('whatever_new_key' => htmlentities($row['value‘])));
```
All right?

**Comment by Jako** [comment]
Change 'whatever_new_key' to your needs.

**Comment by atomoc** [comment]
In phone? I change, but not work...

**Comment by Jako** [comment]
```
$tvValues = new stdObject();
$tvValues->fieldValue = array(array('phone' => htmlentities($row['value'])));
```

**Comment by atomoc** [comment]
```php
        while ($row = $modx->db->getRow($res)) {
            $tvValues = new stdObject();
            $tvValues->fieldValue = array(array('phone' => htmlentities($row['value'])));
            $modx->db->update(array('value' => $modx->db->escape(html_entity_decode(json_encode($tvValues)))), $modx->getFullTableName('site_tmplvar_contentvalues'), 'id=' . $row['id']);
            $output[] = 'Updated ' . $row['contentid'];
        }
```
Not work.

**Comment by Jako** [comment]
Any errors?

**Comment by atomoc** [comment]
PHP Fatal error:  Class 'stdObject' not found in /home/me/www/site/assets/tvs/multitv/updatetv.snippet.php on line 53

**Comment by Jako** [comment]
stdClass

**Comment by atomoc** [comment]
SQL > UPDATE `test`.`modx_site_tmplvar_contentvalues` SET `phone` = '{\"fieldValue\":[{\"phone\":\"
+7 (495) 66-33-880<\\/p>\"}]}' WHERE id=1751

**Comment by atomoc** [comment]
good!!!

**Comment by atomoc** [comment]
I change:
```php
$modx->db->update(array('phone' => $modx->db->escape(html_entity_decode(json_encode($tvValues)))), $modx->getFullTableName('site_tmplvar_contentvalues'), 'id=' . $row['id']);
```
But when corrected phone in to value - works!

**Comment by atomoc** [comment]
Thanks!

**Comment by Jako** [comment]
So this is the solution?
```
while ($row = $modx->db->getRow($res)) {
            $tvValues = new stdObject();
            $tvValues->fieldValue = array(array('phone' => htmlentities($row['value'])));
            $modx->db->update(array('value' => $modx->db->escape(html_entity_decode(json_encode($tvValues)))), $modx->getFullTableName('site_tmplvar_contentvalues'), 'id=' . $row['id']);
            $output[] = 'Updated ' . $row['contentid'];
        }
```

**Comment by atomoc** [comment]
new stdClass

**Comment by Jako** [comment]
ok
