### ISSUE TITLE
Using multicontent

### ISSUE THREAD

**Issue by vmoreira** [Jako/multiTV#122]
Hi jako,
Is possible to use  + (plus) symbol and - (minus) symbol in multidemo to chose 1ª, 2ª, 3ª like image... and not all open at the first time i open the multicontent?

![multicontent](https://cloud.githubusercontent.com/assets/1786615/5962705/91bca5dc-a7dd-11e4-9cf6-3c14063069c8.png)

To use for something like this...

![multicontent1](https://cloud.githubusercontent.com/assets/1786615/5962727/cba08fca-a7dd-11e4-9eb5-e57af45d541a.png)

**Comment by vmoreira** [comment]
Done

**Comment by Nicola1971** [comment]
@vmoreira , very cool. Can I ask you how you did it?

**Comment by vmoreira** [comment]
Hello, I don't do realy like this.

I make a configuration like this
![captura de ecra 2015-06-10 as 18 23 48](https://cloud.githubusercontent.com/assets/1786615/8089229/79d45cc0-0f9e-11e5-8e53-087744fd9b4d.png)

And then it makes a the output in my multiTV like this
![captura de ecra 2015-06-10 as 18 25 57](https://cloud.githubusercontent.com/assets/1786615/8089240/92dad1b8-0f9e-11e5-9ad9-9fd437d4d73a.png)

If I need more just change the configuration document.

**Comment by vmoreira** [comment]
Configuration file in configs:

<?php

//Run snippet

global $modx;

$lingua = $modx->runSnippet('multiTV',array('tvName' =>'10000-LINGUAS-multi','docid' =>'10000','outerTpl' =>'OUTER','rowTpl' =>'@CODE:[+iniciais+]|','display' =>'all','noResults' =>'Sem línguas estrangeiras ativadas'));
$todaslinguas = (explode('|', $lingua, -1));

$linguadescricao = $modx->runSnippet('multiTV',array('tvName' =>'10000-LINGUAS-multi','docid' =>'10000','outerTpl' =>'OUTER','rowTpl' =>'@CODE:[+lingua+]|','display' =>'all','noResults' =>'Sem línguas estrangeiras ativadas'));
$todaslinguasdescricao = (explode('|', $linguadescricao, -1));


$settings['display'] = 'datatable';

$settings['fields'] = array(
//portugues
    'titulo' => array(
        'caption' => 'Título *',
        'type' => 'text'
    ),
    'dia' => array(
        'caption' => 'Dia',
        'type' => 'dropdown',
        'elements' => '||01||02||03||04||05||06||07||08||09||10||11||12||13||14||15||16||17||18||19||20||21||22||23||24||25||26||27||28||29||30||31'
    ),
    'mes' => array(
        'caption' => 'Mês',
        'type' => 'dropdown',
        'elements' => '||Janeiro||Fevereiro||Março||Abril||Maio||Junho||Julho||Agosto||Setembro||Outubro||Novembro||Dezembro'
    ),
    'ano' => array(
        'caption' => 'Ano',
        'type' => 'dropdown',
        'elements' => '||2010||2011||2012||2013||2014||2015||2016||2017||2018||2019||2020',
    ),
    'conteudo' => array(
        'caption' => 'Conteúdo *',
        'type' => 'richtext'
    ),
    'imagem' => array(
        'caption' => 'Imagem',
        'type' => 'image'
    ),
//
    'titulo0' => array(
        'caption' => 'Título (' .($todaslinguasdescricao[0]). ') *',
        'type' => 'text'
    ),
    'lingua0' => array(
        'caption' => 'Conteúdo (' .($todaslinguasdescricao[0]). ') *',
        'type' => 'richtext',
    ),
    'imagem0' => array(
        'caption' => 'Imagem (' .($todaslinguasdescricao[0]). ')',
        'type' => 'image'
    ),
//
    'titulo1' => array(
        'caption' => 'Título (' .($todaslinguasdescricao[1]). ') *',
        'type' => 'text'
    ),
    'lingua1' => array(
        'caption' => 'Conteúdo (' .($todaslinguasdescricao[1]). ') *',
        'type' => 'richtext'
    ),
    'imagem1' => array(
        'caption' => 'Imagem (' .($todaslinguasdescricao[1]). ')',
        'type' => 'image'
    ),
//
    'titulo2' => array(
        'caption' => 'Título (' .($todaslinguasdescricao[2]). ') *',
        'type' => 'text'
    ),
    'lingua2' => array(
        'caption' => 'Conteúdo (' .($todaslinguasdescricao[2]). ') *',
        'type' => 'richtext'
    ),
    'imagem2' => array(
        'caption' => 'Imagem (' .($todaslinguasdescricao[2]). ')',
        'type' => 'image'
    ),
//
    'titulo3' => array(
        'caption' => 'Título (' .($todaslinguasdescricao[3]). ') *',
        'type' => 'text'
    ),
    'lingua3' => array(
        'caption' => 'Conteúdo (' .($todaslinguasdescricao[3]). ') *',
        'type' => 'richtext'
    ),
    'imagem3' => array(
        'caption' => 'Imagem (' .($todaslinguasdescricao[3]). ')',
        'type' => 'image'
    ),
//
    'titulo4' => array(
        'caption' => 'Título (' .($todaslinguasdescricao[4]). ') *',
        'type' => 'text'
    ),
    'lingua4' => array(
        'caption' => 'Conteúdo (' .($todaslinguasdescricao[4]). ') *',
        'type' => 'richtext'
    ),
    'imagem4' => array(
        'caption' => 'Imagem (' .($todaslinguasdescricao[4]). ')',
        'type' => 'image'
    ),
//
    'titulo5' => array(
        'caption' => 'Título (' .($todaslinguasdescricao[5]). ') *',
        'type' => 'text'
    ),
    'lingua5' => array(
        'caption' => 'Conteúdo (' .($todaslinguasdescricao[5]). ') *',
        'type' => 'richtext'
    ),
    'imagem5' => array(
        'caption' => 'Imagem (' .($todaslinguasdescricao[5]). ')',
        'type' => 'image'
    ),
//
    'titulo6' => array(
        'caption' => 'Título (' .($todaslinguasdescricao[6]). ') *',
        'type' => 'text'
    ),
    'lingua6' => array(
        'caption' => 'Conteúdo (' .($todaslinguasdescricao[6]). ') *',
        'type' => 'richtext'
    ),
    'imagem6' => array(
        'caption' => 'Imagem (' .($todaslinguasdescricao[6]). ')',
        'type' => 'image'
    ),
//
    'titulo7' => array(
        'caption' => 'Título (' .($todaslinguasdescricao[7]). ') *',
        'type' => 'text'
    ),
    'lingua7' => array(
        'caption' => 'Conteúdo (' .($todaslinguasdescricao[7]). ') *',
        'type' => 'richtext'
    ),
    'imagem7' => array(
        'caption' => 'Imagem (' .($todaslinguasdescricao[7]). ')',
        'type' => 'image'
    ),
//
    'titulo8' => array(
        'caption' => 'Título (' .($todaslinguasdescricao[8]). ') *',
        'type' => 'text'
    ),
    'lingua8' => array(
        'caption' => 'Conteúdo (' .($todaslinguasdescricao[8]). ') *',
        'type' => 'richtext'
    ),
    'imagem8' => array(
        'caption' => 'Imagem (' .($todaslinguasdescricao[8]). ')',
        'type' => 'image'
    ),
//
    'titulo9' => array(
        'caption' => 'Título (' .($todaslinguasdescricao[9]). ') *',
        'type' => 'text'
    ),
    'lingua9' => array(
        'caption' => 'Conteúdo (' .($todaslinguasdescricao[9]). ') *',
        'type' => 'richtext'
    ),
    'imagem9' => array(
        'caption' => 'Imagem (' .($todaslinguasdescricao[9]). ')',
        'type' => 'image'
    ),

);

$settings['columns'] = array(
    array(
        'caption' => 'Todas as notícias',
        'fieldname' => 'titulo',
        'render' => '<table><tr> <td width="100">[+dia+]-[+mes+]-[+ano+]</td> <td>[+titulo+]</td> </tr></table>'
    )	
);

$data = array(
	'caption' => 'Data',
	'value' => 'newsdata',
	'content' => array(
		'dia' => array(),
		'mes' => array(),
		'ano' => array(),
	),
);

$noticia = array(
	'caption' => 'Notícia',
	'value' => 'conteudo',
	'content' => array(
		'titulo' => array(),
		'conteudo' => array(),
		'imagem' => array(),
	),
);
$lingua0 = array(
	'caption' => $todaslinguas[0],
	'value' => 'lingua0',
	'content' => array( 'titulo0' => array(), 'lingua0' => array(), 'imagem0' => array(), ),
);
$lingua1 = array(
	'caption' => $todaslinguas[1],
	'value' => 'lingua1',
	'content' => array( 'titulo1' => array(), 'lingua1' => array(), 'imagem1' => array(), ),
);
$lingua2 = array(
	'caption' => $todaslinguas[2],
	'value' => 'lingua2',
	'content' => array( 'titulo2' => array(), 'lingua2' => array(), 'imagem2' => array(), ),
);
$lingua3 = array(
	'caption' => $todaslinguas[3],
	'value' => 'lingua3',
	'content' => array( 'titulo3' => array(), 'lingua3' => array(), 'imagem3' => array(), ),
);
$lingua4 = array(
	'caption' => $todaslinguas[4],
	'value' => 'lingua4',
	'content' => array( 'titulo4' => array(), 'lingua4' => array(), 'imagem4' => array(), ),
);
$lingua5 = array(
	'caption' => $todaslinguas[5],
	'value' => 'lingua5',
	'content' => array( 'titulo5' => array(), 'lingua5' => array(), 'imagem5' => array(), ),
);
$lingua6 = array(
	'caption' => $todaslinguas[6],
	'value' => 'lingua6',
	'content' => array( 'titulo6' => array(), 'lingua6' => array(), 'imagem6' => array(), ),
);
$lingua7 = array(
	'caption' => $todaslinguas[7],
	'value' => 'lingua7',
	'content' => array( 'titulo7' => array(), 'lingua7' => array(), 'imagem7' => array(), ),
);
$lingua8 = array(
	'caption' => $todaslinguas[8],
	'value' => 'lingua8',
	'content' => array( 'titulo8' => array(), 'lingua8' => array(), 'imagem8' => array(), ),
);
$lingua9 = array(
	'caption' => $todaslinguas[9],
	'value' => 'lingua2',
	'content' => array( 'titulo9' => array(), 'lingua9' => array(), 'imagem9' => array(), ),
);






if ( $todaslinguas[9] != '') {
$settings['form'] = array(
	$data, $noticia, $lingua0, $lingua1, $lingua2, $lingua3, $lingua4, $lingua5, $lingua6, $lingua7, $lingua8, $lingua9
); }
elseif ( $todaslinguas[8] != '') {
$settings['form'] = array(
	$data, $noticia, $lingua0, $lingua1, $lingua2, $lingua3, $lingua4, $lingua5, $lingua6, $lingua7, $lingua8
); }
elseif ( $todaslinguas[7] != '') {
$settings['form'] = array(
	$data, $noticia, $lingua0, $lingua1, $lingua2, $lingua3, $lingua4, $lingua5, $lingua6, $lingua7
); }
elseif ( $todaslinguas[6] != '') {
$settings['form'] = array(
	$data, $noticia, $lingua0, $lingua1, $lingua2, $lingua3, $lingua4, $lingua5, $lingua6
); }
elseif ( $todaslinguas[5] != '') {
$settings['form'] = array(
	$data, $noticia, $lingua0, $lingua1, $lingua2, $lingua3, $lingua4, $lingua5
); }
elseif ( $todaslinguas[4] != '') {
$settings['form'] = array(
	$data, $noticia, $lingua0, $lingua1, $lingua2, $lingua3, $lingua4
); }
elseif ( $todaslinguas[3] != '') {
$settings['form'] = array(
	$data, $noticia, $lingua0, $lingua1, $lingua2, $lingua3
); }
elseif ( $todaslinguas[2] != '') {
$settings['form'] = array(
	$data, $noticia, $lingua0, $lingua1, $lingua2
); }
elseif ( $todaslinguas[1] != '') {
$settings['form'] = array(
	$data, $noticia, $lingua0, $lingua1
); }
elseif ( $todaslinguas[0] != '') {
$settings['form'] = array(
	$data, $noticia, $lingua0
); }
else  {
$settings['form'] = array(
	$data, $noticia
); }



$settings['configuration'] = array(
    'enablePaste' => false,
    'csvseparator' => ',',
    'radioTabs' => false,
    'hideHeader' => false
);
