### ISSUE TITLE
Enable Paste

### ISSUE THREAD

**Issue by vmoreira** [Jako/multiTV#123]
Hello Jako,
Is possible to use  'enablePaste' => true in configuration $settings['display'] = 'datatable';
I cant use it in paste in datatable but in vertical configuration is Ok. It's normal?

Tks

**Comment by Jako** [comment]
That one is missing in datable script part. 

As a workaround you could switch the config during paste time to ‚vertical‘ and back after.

**Comment by vmoreira** [comment]
Tks Jako for your reply.
