### ISSUE TITLE
Get error if add tabledata value in new resource

### ISSUE THREAD

**Issue by atomoc** [Jako/multiTV#124]
Chrome:
```Uncaught SyntaxError: Unexpected token Д
index.php:1```

Create resource and check again add value nor any error is detected, all is well. But it is still not normal

**Comment by Jako** [comment]
datatable or dbtable mode?

**Comment by atomoc** [comment]
Datatable mode

**Comment by Jako** [comment]
Ok. If I am right, then you have a column renderer active in your config that somehow needs the current resource ID. It is not available in a new resource.

The column renderer should be maybe suppressed in https://github.com/Jako/multiTV/blob/master/assets/tvs/multitv/includes/multitv.class.php#L292-L309 in that case.

**Comment by atomoc** [comment]
I do not know, google translate is not all as it should and I myself do not know some of the words, it's hard. Please tell me whether you can fix it?

**Comment by atomoc** [comment]
I need something like: my father was a worker, a friend of mine is a good man, and so on, I understand)

**Comment by Jako** [comment]
Do you have something this: https://github.com/Jako/multiTV/blob/master/assets/tvs/multitv/configs/links.config.inc.php#L33

**Comment by atomoc** [comment]
Delete this line, the same

**Comment by Jako** [comment]
Should be fixed. The error message was not shown before.

**Comment by atomoc** [comment]
Good! Fixed, and i do not know ) For me not fixed

**Comment by atomoc** [comment]
I wrote that tried to delete a row (L33), and it was no

**Comment by Jako** [comment]
It is fixed. You can't add a line in a multiTV without saving the current resource. Just download the latest [master](https://github.com/Jako/multiTV/archive/master.zip), upload it to your installation and clear the browser cache …

**Comment by atomoc** [comment]
Thank U! Tomorrow will certainly do.

**Comment by atomoc** [comment]
I got it )
