### ISSUE TITLE
Default rows in datatable

### ISSUE THREAD

**Issue by atomoc** [Jako/multiTV#125]
How add default rows in datatable? 

Apparently this is not implemented, but very necessary. I will try, of course, think about the concept, to realize it, but maybe you Jako had some ideas and developments?

**Comment by atomoc** [comment]
Not an easy task. Need to add the ability to specify the color of these lines, to enable them to edit, but not delete, be able to describe them in small print...

**Comment by atomoc** [comment]
How hard is it to do this?

**Comment by Jako** [comment]
Think the delete button could be hidden by css for one TV. Something like #tvidXX .delete { display: none }

**Comment by atomoc** [comment]
Ok, and how add default row?

**Comment by Jako** [comment]
Plugin in onDocFormSave.

**Comment by atomoc** [comment]
I forgot about the plugins) But I need another event, onDocFormPrerender and OnDocFormRender

**Comment by atomoc** [comment]
I am not able to do what I need. 
It is necessary to be able to mark the row and prohibit their removal. How to do it?
Due to CSS is not solved everything. DataTable loaded after my.js, if and loaded before the problem is not solved. Are you good at writing code, but I still do not understand in it.

**Comment by atomoc** [comment]
In general, everything is useless.
