### ISSUE TITLE
Suggestion: Simple solution for multi language Multitv configs

### ISSUE THREAD

**Issue by Nicola1971** [Jako/multiTV#131]
Thinking about a simple solution to share multi language translated Multitv configs:
Just a copy with -lang suffix! and you just need to rename or add a copy of the tv with the -lang suffix:
multicontent-ru, multicontent-it, multicontent-fr, multicontent-es....

IE:
https://github.com/Nicola1971/Youtube-MultiTV-bootstrap/tree/master/assets/tvs/multitv/configs

**Comment by Jako** [comment]
Since config files are PHP you could do a switch on manager_language system settings in one file and fill the array accordingly.
