### ISSUE TITLE
datatable config, error popup "Undefined"

### ISSUE THREAD

**Issue by Fr3ddyCruger** [Jako/multiTV#132]
Good day! there is a problem, there is a window while maintaining swam in datatable config. Though not on all computers.

the window is written: "Undefined"
http://modx.im/uploads/images/00/03/89/2014/11/26/d0c72a.png

modx 1.0.14
multitv (last )

in browser console:

Method getPreventDefault () is deprecated. To replace it, use the method defaultPrevented. jquery-1.8.3.min.js: 2: 0

**Comment by Jako** [comment]
Maybe it is/was a browser cache issue after updating multiTV.
