### ISSUE TITLE
datatable config files does not work with Italian language

### ISSUE THREAD

**Issue by Nicola1971** [Jako/multiTV#133]
links and multicontent are empty when you set italian in evo config
![multitv](https://cloud.githubusercontent.com/assets/7342798/7761057/a0161d24-0021-11e5-8a8a-df1506c5f7ae.jpg)

**Comment by Jako** [comment]
Could you compare the language strings and see which entry causes this? Are there missing ones?

**Comment by Nicola1971** [comment]
yes, there are 3 missing lines in the language file:
* $language['notprepared']
* $language['noidprepare']
* $language['novalue']

Added, but does not solve the issue

**Comment by Nicola1971** [comment]
Seems caused by translation of lines 46-47 
* dataTables.aria.sortAscending
* dataTables.aria.sortDescending

Not sure about the right character coding, but this works for me :
https://github.com/Nicola1971/multiTV/commit/b59635616176f3d81d0d3dce119863c13fc4b3f4

![multitv-fix](https://cloud.githubusercontent.com/assets/7342798/7771005/4fc20a86-0094-11e5-8f7b-207c1b68a33a.jpg)

**Comment by Jako** [comment]
Could you do a PR with that, or please change the strings on Transifex.

**Comment by Nicola1971** [comment]
p.r. done
