### ISSUE TITLE
Ditto pagination and Multitv

### ISSUE THREAD

**Issue by AlexeyMur** [Jako/multiTV#135]
Ditto pagination sitename/news.html?start=1 defines where Multitv starts (I show in sidebar gallery via other [[Ditto? &startID=`11` &tpl=`photosTpl`]] where photosTpl= [[multiTV? &tvName=`photogallery` &docid=`[+id+]` &display=`all`]]).

How to solve problem with ?start=1 ?

**Comment by Jako** [comment]
See: http://jako.github.io/multiTV/snippet.html -> &paginate=`1`
Page key could be defined with &offsetKey.

**Comment by AlexeyMur** [comment]
The problem was solved with &id=`first` of second ditto with Multitv.

**Comment by Jako** [comment]
Then it was a Ditto pagination problem and not a multiTV problem.
