### ISSUE TITLE
Thumbs in datatable mode

### ISSUE THREAD

**Issue by Nicola1971** [Jako/multiTV#137]
Thumbs are not displayed in datatable mode 
ie: default multitv Links config:

![verticalthumb](https://cloud.githubusercontent.com/assets/7342798/8082269/54774414-0f7c-11e5-9898-bf7f40af15db.jpg)

**Comment by Jako** [comment]
Fixed with https://github.com/Jako/multiTV/commit/2b82167ebc635402555661adf85dc79e894945d6
