### ISSUE TITLE
How to call a multiv value in snippet?

### ISSUE THREAD

**Issue by santoshmaharjan** [Jako/multiTV#140]
Hi Jako,

I have created a snippet to remove any space from a multitv value:
Snippet [[removespaces]]

Snippet code:
<?php
$string1 = $modx->getTemplateVarOutput(array('portfoliotype'));
$string = preg_replace('/\s+/', '', $string1);
return $string;
?>

where portfoliotype is the multitv value using text.

But I am not getting any result.

What is the correct way to implement this?

**Comment by Jako** [comment]
Not a multiTV question but do this:
```
$string = preg_replace('/\s+/', '', $string1['portfoliotype']);
```

**Comment by santoshmaharjan** [comment]
Thanks a lot Jako.
