### ISSUE TITLE
options in select boxes seem to have stopped working

### ISSUE THREAD

**Issue by nick0** [Jako/multiTV#142]
Hello Jako,

I have been notified by a website user that their MultiTV select boxes have been behaving wierdly. I tested and also experience the same issue. I tested a totally different site with a simliar config and also had the same problem.

The website is MODx Evo 1.0.15 with MultiTV 2.0.4. The config is at the bottom of this post.

Other than general content edits, no changes have been made to the site - the MODx and MultiTV files remain unchanged. I don't know what is happening.

I am using Firefox 40.0.2.

The issue is as follows: 
If I try to select an option from the select boxes, I can’t seem to be able to choose an option – it’s like the browser doesn’t seem to let me. However, on saving the page and going back in I can see that the colour option that I last hovered on in the variable select menu is selected – just that I can’t see the option being selected at the time of editing until I go back in. Kind of like the click gets stuck.
Very weird.

Here is a screencast: http://screencast-o-matic.com/watch/cojYiTfBla

Any ideas on what might be happening?

Thanks Jako

Config file...

```
$settings['display'] = 'single';
$settings['fields'] = array(
	'age04' => array(
		'caption' => '4',
		'type' => 'dropdown',
		'elements' => '||green||orange||red'
	),
	'age05' => array(
		'caption' => '5',
		'type' => 'dropdown',
		'elements' => '||green||orange||red'
	),
	'age06' => array(
		'caption' => '6',
		'type' => 'dropdown',
		'elements' => '||green||orange||red'
	),
	'age07' => array(
		'caption' => '7',
		'type' => 'dropdown',
		'elements' => '||green||orange||red'
	),
	'age08' => array(
		'caption' => '8',
		'type' => 'dropdown',
		'elements' => '||green||orange||red'
	),
	'age09' => array(
		'caption' => '9',
		'type' => 'dropdown',
		'elements' => '||green||orange||red'
	),
	'age10' => array(
		'caption' => '10',
		'type' => 'dropdown',
		'elements' => '||green||orange||red'
	),
	'age11' => array(
		'caption' => '11',
		'type' => 'dropdown',
		'elements' => '||green||orange||red'
	),
	'age12' => array(
		'caption' => '12',
		'type' => 'dropdown',
		'elements' => '||green||orange||red'
	),
	'age13' => array(
		'caption' => '13',
		'type' => 'dropdown',
		'elements' => '||green||orange||red'
	),
	'age14' => array(
		'caption' => '14',
		'type' => 'dropdown',
		'elements' => '||green||orange||red'
	),
	'age15' => array(
		'caption' => '15',
		'type' => 'dropdown',
		'elements' => '||green||orange||red'
	)
);
$settings['configuration'] = array(
	'enablePaste' => FALSE,
	'enableClear' => FALSE,	
	'csvseparator' => ','
);
```

The multiTV call looks like so
```
[!multiTV?
&tvName=`age`
&docid=`[+id+]`
&outerTpl=`tv-ages-wrapper`
&rowTpl=`tv-ages-row`
&display=`all`
&emptyOutput=`1`
!]
```

**Comment by Jako** [comment]
Have you tried another browser (maybe it is browser specific)?

**Comment by nick0** [comment]
Good question Jako.

I just tried the following and all seemed aok:
Opera 31.0.1889.174 = fine
IE 11.0.9600.17937 = fine
Chrome 44.0.2403.155 m = fine

I am unable to check what version the website user is using.

The problem appears isolated to:
Firefox (I am using version 40.0.2)

Any thoughts?

**Comment by Jako** [comment]
Maybe a CSS issue. Could you check that with Firebug?

**Comment by nick0** [comment]
Hmmm. I have never used Firebug - I installed it and had a look but not sure how really what I am looking for. When I interact with the selectboxes I can see the css and html but can't see any errors listed - but I may be using it wrong

I tried another Firefox add on called Web Developer tools - the only warning I can see is:
The Web Console logging API (console.log, console.info, console.warn, console.error) has been disabled by a script on this page.
That may not even be relevant.

Can you talk me through Firebug Jako? Maybe then I will be able to find the error?

**Comment by Jako** [comment]
Fixed with https://github.com/Jako/multiTV/commit/e41f1f1123c5f599221499293c20cecf77723378

**Comment by nick0** [comment]
Wow, well done Jako. That seems to have fixed the issue. Select boxes now work again as expected in Firefox (40.0.2). Many thanks.
