### ISSUE TITLE
Inherit multiTV dropdown from other multiTV-tv (on another page)

### ISSUE THREAD

**Issue by janniconl** [Jako/multiTV#143]
Hi Jako,

First of all thanks for developing this great addition to Evo! Maintaining about 40 Evo installations I'm using multiTV a lot. It really enhances the Evo interface for my users.

I was wondering if you help me a little bit with the following issue. I'm trying to populate a multiTV dropdown with values from another multiTV template variable on another page. But somehow I can not manage to make it work. I've already looked at your examples and some of the issues on this Guthub.

I am trying to show locations (from tv 1) in another tv on a different page (tv 2) where you can set a date and a location for a event.
Here is my setup:

TV 1 (Resource ID 1, template ID 1) - Source list
---------------------------------
`course_locations.config.inc.php`
```
<?php
$settings['display'] = 'horizontal';
$settings['fields'] = array(
    'city' => array(
        'caption' => 'Plaats',
        'type' => 'text',
        'width' => '180'
    ),
    'name' => array(
        'caption' => 'Naam locatie (optioneel)',
        'type' => 'text',
        'width' => '180'
    ),
    'address' => array(
        'caption' => 'Adres',
        'type' => 'text',
        'width' => '250'
    ),
    'url' => array(
        'caption' => 'Website',
        'type' => 'text',
        'width' => '250'
    ),
);
$settings['templates'] = array(
    'outerTpl' => '[+wrapper+]',
    'rowTpl' => '[+city+], [+name+]'
);
$settings['configuration'] = array(
    'enablePaste' => false,
    'enableClear' => false,
    'csvseparator' => ','
);
```

TV 2 (Resource ID 2, template ID 2) - List to be populated by source
---------------------------------

`course_date_location.config.inc.php`
```
<?php
$settings['display'] = 'horizontal';
$settings['fields'] = array(
    'locations' => array(
        'caption' => 'Locatie',
        'type' => 'dropdown',
        'elements' => "@EVAL return $modx->runSnippet('multiTV', array(
            'tvName' =>'course_locations',
            'docid' =>'1',
            'outerTpl' =>'@CODE:[+wrapper+]',
            'rowTpl' =>'@CODE:[+name+] [+city+]||',
            'display' =>'all')
        );",
    ),
    'date' => array(
        'caption' => 'Startdatum',
        'type' => 'date'
    ),
);
$settings['templates'] = array(
    'outerTpl' => '[+wrapper+]',
    'rowTpl' => '[+locations+]'
);
$settings['configuration'] = array(
    'enablePaste' => false,
    'enableClear' => true,
    'csvseparator' => ','
);

/*
[!multiTV?
&tvName=`course_locations`
&docid=`1`
&outerTpl=`@CODE:((wrapper))`
&rowTpl=`@CODE:[+name+] [+city+]||`
&display=`all`
!]

Result: Location 1 City||Location 2 City||Location 3 City||
*/

/*
https://github.com/Jako/multiTV/blob/master/assets/tvs/multitv/configs/sidebar.config.inc.php
https://github.com/Jako/multiTV/issues/141
*/
```

Somehow I keep getting a parse error:
`Parse error: syntax error, unexpected ',' in /home/user/domains/[DOMAINNAME]/public_html/manager/includes/tmplvars.commands.inc.php(64) : eval()'d code on line 1`

![error](https://cloud.githubusercontent.com/assets/1488614/10261894/cab6e840-69af-11e5-93dc-22ffccbcbfc1.png)

Can you see any errors in my syntax?
Any idea why I am not seeing results in the dropdown in TV2? (FYI: TV1 on is populated with 3 locations)

**Comment by janniconl** [comment]
When I run this as a normal TV in MODx (with type dropdown) I get my results as expected:

````
@EVAL return $modx->runSnippet('multiTV', array(
  'tvName' =>'course_locations',
  'docid' =>'1',
  'outerTpl' =>'@CODE:[+wrapper+]',
  'rowTpl' =>'@CODE:[+name+] [+city+]',
  'outputSeparator' =>'||',
  'display' =>'all'
));
````

The point in `manager/includes/tmplvars.commands.inc.php` where it seems to fail is around this code (line 63-65):
````
            case "EVAL" : // evaluates text as php codes return the results
                $output = eval ($param);
                break;
````

**Comment by janniconl** [comment]
P.s. Im using EVO 1.0.15 and multiTV 2.0.5

**Comment by janniconl** [comment]
OK, managed to get it to work, after reading your work at http://docs.evolution-cms.com/Extras/Snippets/multiTV and with a little help of my previous Evo experiences ;-).

`MODX does not like =, ? and & in snippet parameters. If the template code has to use those signs, put the template code in a chunk or change the default templates in the config file.`

- I now placed the php to run `$modx->runSnippet` (as stated above) in a seperate snippet called `get_locations`
- In my multiTV config I changed to this `'elements' => '@EVAL return $modx->runSnippet("dob_get_locations", array());`
- Had to prevent a PHx error like mentioned here http://forums.modx.com/thread/45374/phx-fresh-install-fatal-error-cannot-redeclare-class#dis-post-262132

Although the error is not really fixed, the issue is. So you can close this thread if you want.

**Comment by Jako** [comment]
Why don't you use the original docs from http://jako.github.io/multiTV/snippet/?

Since the configs are PHP code you could use this in the course_date_location.config.inc.php
```
$settings['fields'] = array(
    'locations' => array(
        'caption' => 'Locatie',
        'type' => 'dropdown',
        'elements' => $modx->runSnippet('multiTV', array(
            'tvName' => 'course_locations',
            'docid' => '1',
            'outerTpl' => '@CODE:[+wrapper+]',
            'rowTpl' => '@CODE:[+name+] [+city+]',
            'outputSeparator' => '||'
            'display' => 'all')
        ),
    ),
```

**Comment by janniconl** [comment]
1. I use all the docs I can find. Including the ones on your website :)

2. If you read my FIRST post (carefully): the solution you mention is exactly what I was doing and the reason I was making this thread. Because the solution you mention did not work for me :'(

**Comment by Jako** [comment]
You could use the runSnippet without @EVAL and quotes arouns, and you could use the outputSeparator parameter for the multiTV snippet that avoids the last ||. That are the differences in my code.

**Comment by janniconl** [comment]
Ah did not notice that difference in your code, sorry my bad. Thanks mate. Yeah, figured the outputSeparator out later on, good to know. Anyways thanks for your help! Cheers

**Comment by Jako** [comment]
The sentence you have mentioned is at the end of the page (http://jako.github.io/multiTV/snippet/#fn:1). And I don't think that this is the issue that occured. Maybe @EVAL does not like line feeds.

**Comment by janniconl** [comment]
Ah good to know! Like I said, I'm usually using all resources I can find ;-)
