### ISSUE TITLE
Show xxx if a field is empty else show yyyy

### ISSUE THREAD

**Issue by santoshmaharjan** [Jako/multiTV#144]
Hi Jako, how do I output the following condition:
If any or one of the fields in a config file is blank, show xxx else yyy in the frontend. I have the following situation - a rowtpl with linktext and linkurl. If the linkurl field is left empty, show chunk1, if filled show chunk2 in the frontend. Thanks.

**Comment by Jako** [comment]
```
[[+linkurl:ne=``:then=`{chunk1}`:else=`{chunk2}`]]
```

**Comment by santoshmaharjan** [comment]
Hi Jako,

Somehow it did not work.

I have called MultiTV the following way:

    [!multiTV?
    &tvName=`scrollingnews`
    &docid=`13`
    &outerTpl=`scrollingnewsouterTpl`
    &rowTpl=`scrollingnewsrowTpl`
    &display=`all`
    &rows=`all`!]

scrollingnews.config.inc.php

    <?php
    $settings['display'] = 'vertical';
    $settings['fields'] = array(
     'newstitle' => array(
     'caption' => 'News Title',
    'type' => 'text'
    ),
    'linkurl' => array(
    'caption' => 'Link to URL',
    'type' => 'text',
    )
    );
scrollingnewsouterTpl

    <ul id="newsticker_reveal" class="newsticker">[+wrapper+]</ul> 

scrollingnewsrowTpl

    [[+linkurl:ne=``:then=`<li><a href="[~[+linktourl+]~]">[+newstitle+]</a></li>`:else=`<li>[+newstitle+]</li>`]]

I tried the above code with + at the end too.

It outputs blank. What am I doing wrong?

**Comment by Jako** [comment]
Too much Revo in my head. [+ +] instead of [[+ ]]

**Comment by santoshmaharjan** [comment]
Thanks a lot jako. Works beautifully.
