### ISSUE TITLE
No thumb in horizontal type

### ISSUE THREAD

**Issue by dmi3yy** [Jako/multiTV#145]
http://take.ms/FMgF0

**Comment by Jako** [comment]
The thumbnail is inserted in the DOM by javascript. There is no different handling between the display types. Maybe a missing thumbof in the config?

**Comment by dmi3yy** [comment]
change  only type  vertical to horizontal and no thumb

**Comment by dmi3yy** [comment]
now all ok 
http://take.ms/TaS0k

**Comment by Jako** [comment]
Thanks for the fix.
