### ISSUE TITLE
can't click append

### ISSUE THREAD

**Issue by mgzawlinoo** [Jako/multiTV#148]
Hi, 
I can add data in localhost, but not in my server (Hostgator).
at server , I can choose image, enter data , but can't click Append.
php version is different in each server , (Local - 5.6) , (hostgator - 5.3)
![append](https://cloud.githubusercontent.com/assets/9032715/11958345/d2ee9bea-a8f5-11e5-9a53-fe8bf744bdb9.jpg)

I have another question for multiTV.
Can I add a ID for each row ? 
eg . I add ten row and ID 1-10 is show at first.

Can I show Default show to 10 from 25?
that all .
Really thanks for develop MultiTV and it save a lot of my projects.

Thank you . Sorry for my english.

**Comment by Jako** [comment]
What display mode uses this multiTV?

**Comment by mgzawlinoo** [comment]
I use databale, modx ver: 1.0.15.
<?php
$settings['display'] = 'datatable';
$settings['fields'] = array(
    'image' => array(
        'caption' => 'Image',
        'type' => 'image'
    ),
    'thumb' => array(
        'caption' => 'Thumbnail',
        'type' => 'thumb',
        'thumbof' => 'image'
    ),
    'title' => array(
        'caption' => 'Title',
        'type' => 'text'
    )
);
$settings['columns'] = array(
    array(
        'caption' => 'Images',
        'fieldname' => 'title',
        'render' => '<strong>[+title+]</strong>'
    ),
	    array(
		 'caption' => 'Path',
        'fieldname' => 'image',
        'render' => '<strong>[+image+]</strong>'
    )
);

$settings['form'] = array(
    array(
        'caption' => 'Image',
        'content' => array(
            'image' => array(),
            'title' => array()
        )
    )
);

Thank you jako.

**Comment by Jako** [comment]
That should be caused somehow by the 'render' setting of the columns. Could you deactivate the setting and try it without to check that, please.
