### ISSUE TITLE
If I am not using tinyMCE I can not close modal (datatable mode)

### ISSUE THREAD

**Issue by janniconl** [Jako/multiTV#152]
Hi Jako,

I am **not** using tinyMCE (disabled). I have codeMirror enabled for supported textarea's.

When I set up a TV using the datatable mode, I can add a new tv-value, but after that I can not close the modal, due to a JS error in FireFox: 
`ReferenceError: tinyMCE is not defined | multitv.js (regel 981, kol 25)`

This prevents the modal from being closed.

When I enable TinyMCE all works fine. 

How can I use the datatable mode for multiTV, but while not using TinyMCE?

**Comment by Jako** [comment]
Does the config contains a 'richtext' field? Otherwise the tabEditor class is not assigned which triggers the multitv script to reference the tinyMCE object.

**Comment by janniconl** [comment]
Ah yes it is. Stupid of me.

The problem is my clients use the TinyMCE. So they have it enabled. I don't, since I am fine working with HTML. I guess it will be too much work to check if tinyMCE is enabled (defined) :)

**Comment by janniconl** [comment]
While we are at it, is there any way I can use TinyMCE 4 in the datatable modal?
I have it installed as my default wysiwyg. Also see #119

**Comment by Deesen** [comment]
Reg TinyMCE4, if you are on latest MultiTV and latest Modx-Dev version it should work.

**Comment by Jako** [comment]
Please create a new issue for TinyMCE in datatable modal.

**Comment by janniconl** [comment]
Great thx! Works for me now with the latest versions of TinyMCE, multiTV and Modx evo dev.
