### ISSUE TITLE
Pagination issue with ? in the URL

### ISSUE THREAD

**Issue by santoshmaharjan** [Jako/multiTV#154]
Hi Jako,
While using pagination, the pagination link URL uses `?` which does not lead to the next page, instead goes to the home page. But using `&` works fine. How do I replace the `?` with `&`?
Example:
`index.php?id=11?page=2` - Does not work
`index.php?id=11&page=2` - Works

Since I am using PHX, could that be the reason? What should I do in order to keep on using the default `?`

I am using MODX 1.1

Regards,
Santosh

**Comment by Deesen** [comment]
Maybe this is the solution? https://github.com/Deesen/evolution/commit/16dee097a9ae0d6ecc0ee2a7af0b7a8571caac0c

**Comment by santoshmaharjan** [comment]
Thanks Deesen.
