### ISSUE TITLE
Is it possible to support TinyMCE (4) themes in modals?

### ISSUE THREAD

**Issue by janniconl** [Jako/multiTV#156]
Hi Jako,

Just wondering. The latest MODx1.1 with TinyMCE 4 now supports different TinyMCE theme's per TV. Is it possible for you to support this in multiTV as well?

Also see: 
- https://github.com/Deesen/tinymce4-for-modx-evo/
- https://github.com/Deesen/tinymce4-for-modx-evo/tree/master/assets/plugins/tinymce4/theme

So, something like:
````
  $settings['fields'] = array(

    'faq_content' => array(
        'caption' => 'Content',
        'type' => 'richtext',
        'theme' => 'mini'
    ),
          [.....]
  );
````

Would be awesome!

**Comment by Deesen** [comment]
Yes it is possible of course but needs a little bit of attention first ;-)..

**Comment by janniconl** [comment]
Nice :-) Would be great. I'll leave this to you guys (Jako) though, since I would not really know where to begin :S 

Let me know if I can help by doing some testing.

**Comment by janniconl** [comment]
For now I've hacked the multitv.js (https://github.com/Jako/multiTV/blob/master/assets/tvs/multitv/js/multitv.js)

and added my own rules (since all my multitv TV's can share the following config) until there is a better and built-in solution for MultiTV. Might be of some help for others.

After r.991 i've added:
````
// Custom settings (hack)
configObj['plugins'] = 'paste charmap code';
configObj['toolbar1'] = 'undo redo | paste pastetext | bold italic underline strikethrough | charmap | bullist numlist | removeformat | code';
configObj['toolbar2'] = '';
configObj['invalid_elements'] = 'h1,h2,table,th,td[colspan|rowspan],tr,thead,tfoot,tbody,figure,img,blockquote,pre,code';
configObj['browser_spellcheck'] = true;   
````

**Comment by Deesen** [comment]
I added this feature today. Needs latest MODX-dev and latest TinyMCE4 so until commits are not merged you can find them here :

https://github.com/Deesen/tinymce4-for-modx-evo
https://github.com/Deesen/evolution

    $settings['fields'] = array(
      'content1_1' => array(
        'caption' => 'Content',
        'type' => 'richtext',
        'theme'=>'mini'        
      ),
    );

**Comment by janniconl** [comment]
Great addition, thx! Will test it asap
