### ISSUE TITLE
css style for input[type='checkbox']

### ISSUE THREAD

**Issue by Fr3ddy7** [Jako/multiTV#161]
http://postimg.org/gallery/16jrq0d5a/

I propose to make changes in the css styles for checkboxes. Now they have no flow. I did not want to touch the formation of the list to add the "label" for proper flow and made a clean css, with the addition of classes (which is very crooked)

I think it will improve the visual *multitv*
and thank you for this great "tool", without him is hard to imagine MODX 8)))

**Comment by Deesen** [comment]
Maybe MultiTV should check if `assets/tvs/multitv/css/multitv_custom.css` exists and add it after `multitv.css`, so everybody can customize CSS when needed, and the file does not get overwritten after updating.
