### ISSUE TITLE
sorting in datatable config

### ISSUE THREAD

**Issue by Fr3ddy7** [Jako/multiTV#163]
datatable config (last evo from git + last multitv) 

sorting not working, 3 sites. after saving nothing happens, everything is back in its place

**Comment by Deesen** [comment]
I can confirm. After moving a row a error pops up in console: `TypeError: ui.item.context is undefined`

**Comment by Deesen** [comment]
@Jako : I am not sure what is the root-cause of this issue and since when it happened. When I do the following, row-reordering works again: In `jquery-dataTables.rowReordering-1.1.0.js`, line 222-end I replaced `ui.item.context.id` by `ui.item[0].id`.

**Comment by Fr3ddy7** [comment]
@Jako ?)

**Comment by Deesen** [comment]
I guess I found the reason. On 19.07. jQuery got updated to v3.1 and is loaded by default in MODX Manager. So it seems jquery-ui-1.10.4.custom.min.js is not compatible with 3.1.

**Comment by Fr3ddy7** [comment]
just I tried it in another manager theme, modxpress
everything is working. No errors and conflicts. Mystic)

switch to modxre - does not work

**Comment by Fr3ddy7** [comment]
+ in template connect the old version 1.8.3 :(

**Comment by dmi3yy** [comment]
https://github.com/modxcms/evolution/issues/869 

its the same bug

**Comment by Deesen** [comment]
Sure? Our sort-icons where visible and useable, but the new order would not be saved to DB.

**Comment by Jako** [comment]
Should be fixed now.

**Comment by Deesen** [comment]
Thanks!

**Comment by Fr3ddy7** [comment]
Thanks!

**Comment by Jako** [comment]
Who updates the package on http://extras.evolution-cms.com/ ?

**Comment by dmi3yy** [comment]
I do this tomorrow

Отправлено с iPhone
