### ISSUE TITLE
The proposal to improve the iteration in the multiTV

### ISSUE THREAD

**Issue by Azariil** [Jako/multiTV#170]
Sorry for my English.
Sometimes there are tasks in which it is necessary to begin iteration not with 1, and with 0.
I propose to add to the snippet parameter for the iteration.

`$params['iteration'] = (isset($iteration)) ? intval($iteration) : 1;`

And multitv.class.php file replace line 1061:

`$i = $iteration = 1;`

on line:

`$i = $iteration = $params['iteration'];`

The idea is not to break compatibility and adds new functionality.

**Comment by Jako** [comment]
could you do math on the placeholder?

```
[+iteration:math=`?-1`+]
```

**Comment by Azariil** [comment]
I forgot about phx (they rarely use). Thank you.
