### ISSUE TITLE
[+rows.total+] not working any more

### ISSUE THREAD

**Issue by leonie12** [Jako/multiTV#171]
I have something in the form of `[+rows.total:eq=`1`:then=`xxx`:else=`yyy`+]` in one of my websites. It worked until recently. Now there seems to be no output any more.
Even `[+rows.total+]` in some multitv.config.inc.php does not output anything.

Was there a change in the code that induced this behaviour and is this supposed to be this way?

**Comment by leonie12** [comment]
Yes, phx installed. It worked for some years.

**Comment by Deesen** [comment]
@leonie12 Please better report to https://github.com/modxcms/evolution/issues as there have been quite some changes to the core. It probably has to do with it.
