### ISSUE TITLE
import csv in vertical config

### ISSUE THREAD

**Issue by Fr3ddy7** [Jako/multiTV#175]
Hello Jako =)
have is a problem is found on all sites. (The latest version)
when you import data, normally adds only 318 lines, 319 produces an error.

`« MODX Parse Error »
Execution of a query to the database failed - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' cacheable=, editedby=1, editedon=1485526875, publishedon=publishedon, published' at line 1`

csv data, separator = ;

`130-3101012;Диск колесный с кольцами ЗИЛ 130 (пр-во Россия);3565
453-3716;Знак аварийный улучшенный (1-й сорт)(пр-во Украина);130
453-3716;Знак аварийный улучшенный (2-й сорт)(пр-во Украина);93
453-3716;Знак аварийный улучшенный (пр-во Украина);206`

![zil-gaz com ua - modx cms manager](https://cloud.githubusercontent.com/assets/8958344/22382574/e1f9c018-e4ce-11e6-81bc-46d192c9696b.jpg)

the impression is that any restriction on the data to add

**Comment by Jako** [comment]
Sorry, I have no idea on this at the moment.

**Comment by Fr3ddy7** [comment]
The impression is that there is a limit of 318 lines))

**Comment by Jako** [comment]
Could be a restriction to $_POST length or similar.
