### ISSUE TITLE
Type 'dropdown' does not save with manual values, only @SELECT

### ISSUE THREAD

**Issue by ricardo-lewis** [Jako/multiTV#178]
I'm using the following TV element:
```
'box-type' => array(
	   'caption' => 'Type',
	   'type' => 'dropdown',
	   'elements' => 'Red==red||Green==red||Blue==red||Custom==custom' 
    )
```
It displays correctly in the MODX Manager, but the selected value is never saved. The database TV value shows it saved the first value 'red'.

Other fields in that same TV config save correctly.

However, using @ SELECT to generate the rows does work:
```
	   'elements' => '@SELECT "Red" as `pagetitle`,"red" as `id`  UNION SELECT "Green" as `pagetitle`,"green" as `id` ' 

```

MODX 1.2.1
Ubuntu 14.04
Apache 2.4.7
PHP 5.5.9
MySQL 5.6.33

**Comment by Jako** [comment]
Sorry, I have no idea on this at the moment. Maybe it is a similar issue as #176

**Comment by Jako** [comment]
Two values of a dropdown TV can't have the same value.
