### ISSUE TITLE
Thumbnails do not work in the output [+thumb+]

### ISSUE THREAD

**Issue by Zem-serg** [Jako/multiTV#181]
Standard Config multidemo.config.inc.php

`$settings['templates'] = array(
    'outerTpl' => '<ul>[+wrapper+]</ul>',
    'rowTpl' => '<li>[+text+], [+image+], [+thumb+], [+textarea+], [+date+], [+dropdown+], [+listbox+], [+listbox-multiple+], [+checkbox+], [+option+]</li>'
);`

In the admin panel everything is ok, there is no url on the page before the image (thumb)

`<ul><li>Test text, assets/images/11.jpg, , test test test , 02-05-2017 17:26:14, 1, 2, Orange, , </li></ul>`

... 11.jpg, ????? , test.......

Is there a solution on how to display a preview of the image on the page?

**Comment by Jako** [comment]
`[+thumb+]` is a virtual placeholder that's just used in the MODX backend. It makes no sense to use it in the frontend since it is restricted to max width or height of 150px by default.

Use the `[+image+]` in conjunction with phpthumb modifier/snippet.
