### ISSUE TITLE
Checkbox seperator

### ISSUE THREAD

**Issue by fourroses666** [Jako/multiTV#182]
I would like to change the seperator for my multiple checkbox.

My call
```
[!multiTV?
&tvName=`sites`
&docid=`[*id*]`
&outerTpl=`@CODE:((wrapper))`
&rowTpl=`@CODE:((opties))`
&toPlaceholder=`0`
!]
```

My config for sites;
```$settings['display'] = 'datatable';
$settings['fields'] = array(
    'opties' => array(
        'caption' => 'Opties',
        'type' => 'checkbox',
		'elements' => 'First==1||Second==2||Third==3||Fourth==4'
    )
);
$settings['form'] = array(
    array(
        'caption' => 'Opties:',
        'content' => array(
            'opties' => array()
        )
    )
);

```

On my site when selecting multiple checkboxes it shows the **,** as seperator. -> 1,3,4
Is there a way to remove the **,** from the ((opties)) output? -> 1 3 4

&outputSeparator=`` is for the total row and not the checkbox

**Comment by Deesen** [comment]
Maybe use a chunk and a custom snippet called "searchReplace" inside a rowTpl-chunk with the following call / code?
```
// [[searchReplace?&string=`[+opties+]`&search=`,`&replace=` `]]
return str_replace($string, $search, $replace);
```

**Comment by fourroses666** [comment]
Thanks Dennis, works great!
