### ISSUE TITLE
rowReordering

### ISSUE THREAD

**Issue by AndrewMInsk** [Jako/multiTV#186]
In the latest versions of MODX Evo there is a bug with Multi TV - sorting is not working in datatable mode (the drag and drop is working, but when you save the order is not saved). I corrected a little code there, and everything works now. How do I implement this into the Multi -TV repository?
/assets/tvs/multitv/js/jquery-dataTables.rowReordering-1.1.0.js
About 250 lines
FnMoveRows (sSelector, oState.iCurrentPosition, oState.iNewPosition, oState.sDirection, ui.item.context.id, sGroup);
Replaced by
FnMoveRows (sSelector, oState.iCurrentPosition, oState.iNewPosition, oState.sDirection, ui.item [0] .id, sGroup);

**Comment by fourroses666** [comment]
https://github.com/Jako/multiTV/issues/183

**Comment by Jako** [comment]
Should be fixed with https://github.com/Jako/multiTV/commit/392e72336041d20a463200d3982b2ee7170e5b12 

Sadly the fork on https://github.com/extras-evolution seems to be handled without using this repository.
